fix: :bug: fix bug

diff --git a/ansible/install-gnome-extensions.yml b/ansible/install-gnome-extensions.yml
--- a/ansible/install-gnome-extensions.yml
+++ b/ansible/install-gnome-extensions.yml
@@ -19,17 +19,26 @@
 
     - name: Loop through extension_urls and download files
       shell: |
-        TARGET_DIR="~/.local/share/gnome-shell/extensions/"
-        cd "$TARGET_DIR"
+        TARGET_DIR="~/.local/share/gnome-shell/extensions"
         URL_OF_YOUR_ZIP_FILE="{{ item }}"
         ZIP_FILE=$(basename "$URL_OF_YOUR_ZIP_FILE")
+
+        # Change to the target directory
+        cd "$TARGET_DIR" || { echo "Failed to change directory"; exit 1; }
+
+        # Download the ZIP file
         curl -o "$ZIP_FILE" "$URL_OF_YOUR_ZIP_FILE"
+
+        # Extract the UUID from metadata.json
         UUID=$(unzip -p "$ZIP_FILE" metadata.json | jq -r .uuid)
+
         echo ":::::::::::::::"
         echo "URL $URL_OF_YOUR_ZIP_FILE"
-        echo "zip $ZIP_FILE"
+        echo "ZIP $ZIP_FILE"
         echo "UUID: $UUID"
+        echo "TARGET FOLDER $TARGET_DIR"
         echo ":::::::::::::::"
+
         if [ ! -z "$UUID" ]; then
           mkdir -p "$UUID"
           mv "$ZIP_FILE" "$UUID"
